name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  checks: write

jobs:
  check:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "zulu"

      - name: Add permissions
        run: chmod +x ./gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          generate-job-summary: false

      - name: Check
        run: ./gradlew check

      - name: Generate test coverage
        shell: bash
        run: |
          COVERAGE=$(./gradlew :koverLog | grep "application line coverage:" | tail -n1 | cut -d ":" -f 2 | tr -d '[:space:]%')
          echo "COVERAGE=$(echo $COVERAGE)" >> $GITHUB_ENV

      - name: Update dynamic badge gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6bf1b7a292bc61bcca966bee22e8b456
          filename: coverage-badge.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
